# Generated by Django 5.0 on 2024-06-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0008_formulaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
