# Generated by Django 5.0 on 2024-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='duree',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
