# Generated by Django 5.0 on 2024-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0012_servicedemande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone_client', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
