# Generated by Django 5.0 on 2024-06-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0014_appointment_service_delete_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
