# Generated by Django 5.0 on 2024-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0015_remove_appointment_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
