# Generated by Django 5.0 on 2024-06-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0019_votremodele'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=100)),
                ('detail_description', models.TextField()),
                ('detail_image', models.ImageField(upload_to='project_detail_images/')),
                ('detail_video', models.FileField(upload_to='project_detail_videos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventApp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='VotreModele',
        ),
    ]
