# Generated by Django 5.0 on 2024-06-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0020_projectdetail_delete_votremodele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='country',
        ),
    ]
