# Generated by Django 5.0 on 2024-06-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0021_remove_appointment_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='detail_video',
        ),
    ]
