# Generated by Django 5.0 on 2024-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0023_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotreModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(default='valeur_par_defaut', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(default=''),
        ),
    ]
